/** Alphabetically sorted U.S. higher-ed names for autocomplete (demo data). */
const US_UNIVERSITIES_UNSORTED = [
  'Adelphi University',
  'American University',
  'Amherst College',
  'Arizona State University',
  'Auburn University',
  'Babson College',
  'Ball State University',
  'Barnard College',
  'Baylor University',
  'Belmont University',
  'Binghamton University, SUNY',
  'Boston College',
  'Boston University',
  'Bowdoin College',
  'Brandeis University',
  'Brigham Young University',
  'Brown University',
  'Bryant University',
  'Bucknell University',
  'California Institute of Technology',
  'California Polytechnic State University, San Luis Obispo',
  'California State University, Fullerton',
  'California State University, Long Beach',
  'California State University, Northridge',
  'Carnegie Mellon University',
  'Case Western Reserve University',
  'Catholic University of America',
  'Chapman University',
  'Claremont McKenna College',
  'Clemson University',
  'Colby College',
  'Colgate University',
  'College of Charleston',
  'College of William & Mary',
  'Colorado School of Mines',
  'Colorado State University',
  'Columbia University',
  'Connecticut College',
  'Cornell University',
  'Creighton University',
  'Dartmouth College',
  'Davidson College',
  'DePaul University',
  'Drexel University',
  'Duke University',
  'Elon University',
  'Emerson College',
  'Emory University',
  'Florida Atlantic University',
  'Florida International University',
  'Florida State University',
  'Fordham University',
  'George Mason University',
  'George Washington University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Georgia State University',
  'Gonzaga University',
  'Grand Valley State University',
  'Harvard University',
  'Harvey Mudd College',
  'Haverford College',
  'Howard University',
  'Illinois Institute of Technology',
  'Illinois State University',
  'Indiana University Bloomington',
  'Iowa State University',
  'James Madison University',
  'Johns Hopkins University',
  'Kansas State University',
  'Kennesaw State University',
  'Kent State University',
  'Lehigh University',
  'Liberty University',
  'Louisiana State University',
  'Loyola Marymount University',
  'Loyola University Chicago',
  'Loyola University Maryland',
  'Marquette University',
  'Massachusetts Institute of Technology',
  'Miami University',
  'Michigan State University',
  'Middlebury College',
  'Mississippi State University',
  'Montana State University',
  'New Jersey Institute of Technology',
  'New York University',
  'North Carolina State University',
  'Northeastern University',
  'Northern Arizona University',
  'Northwestern University',
  'Ohio State University',
  'Ohio University',
  'Oklahoma State University',
  'Oregon State University',
  'Pace University',
  'Pennsylvania State University',
  'Pepperdine University',
  'Portland State University',
  'Princeton University',
  'Purdue University',
  'Rensselaer Polytechnic Institute',
  'Rice University',
  'Rochester Institute of Technology',
  'Rollins College',
  'Rutgers University–New Brunswick',
  'Saint Louis University',
  'San Diego State University',
  'San Francisco State University',
  'San Jose State University',
  'Santa Clara University',
  'Seattle University',
  'Seton Hall University',
  'Southern Methodist University',
  'Stanford University',
  'Stevens Institute of Technology',
  'Stony Brook University, SUNY',
  'Syracuse University',
  'Temple University',
  'Texas A&M University',
  'Texas Christian University',
  'Texas State University',
  'Texas Tech University',
  'The Citadel',
  'The Ohio State University',
  'Tufts University',
  'Tulane University',
  'University at Albany, SUNY',
  'University at Buffalo, SUNY',
  'University of Alabama',
  'University of Alabama at Birmingham',
  'University of Arizona',
  'University of Arkansas',
  'University of California, Berkeley',
  'University of California, Davis',
  'University of California, Irvine',
  'University of California, Los Angeles',
  'University of California, Riverside',
  'University of California, San Diego',
  'University of California, Santa Barbara',
  'University of California, Santa Cruz',
  'University of Central Florida',
  'University of Chicago',
  'University of Cincinnati',
  'University of Colorado Boulder',
  'University of Colorado Denver',
  'University of Connecticut',
  'University of Dayton',
  'University of Delaware',
  'University of Denver',
  'University of Florida',
  'University of Georgia',
  'University of Hawaii at Mānoa',
  'University of Houston',
  'University of Idaho',
  'University of Illinois Chicago',
  'University of Illinois Urbana-Champaign',
  'University of Iowa',
  'University of Kansas',
  'University of Kentucky',
  'University of Louisiana at Lafayette',
  'University of Louisville',
  'University of Maine',
  'University of Maryland, Baltimore County',
  'University of Maryland, College Park',
  'University of Massachusetts Amherst',
  'University of Massachusetts Lowell',
  'University of Miami',
  'University of Michigan',
  'University of Minnesota, Twin Cities',
  'University of Mississippi',
  'University of Missouri',
  'University of Montana',
  'University of Nebraska–Lincoln',
  'University of Nevada, Las Vegas',
  'University of Nevada, Reno',
  'University of New Hampshire',
  'University of New Mexico',
  'University of North Carolina at Chapel Hill',
  'University of North Carolina at Charlotte',
  'University of North Dakota',
  'University of North Florida',
  'University of North Texas',
  'University of Notre Dame',
  'University of Oklahoma',
  'University of Oregon',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of Rhode Island',
  'University of Richmond',
  'University of Rochester',
  'University of San Diego',
  'University of San Francisco',
  'University of South Carolina',
  'University of South Florida',
  'University of Southern California',
  'University of Tennessee, Knoxville',
  'University of Texas at Arlington',
  'University of Texas at Austin',
  'University of Texas at Dallas',
  'University of Texas at El Paso',
  'University of Texas at San Antonio',
  'University of Utah',
  'University of Vermont',
  'University of Virginia',
  'University of Washington',
  'University of Wisconsin–Madison',
  'University of Wisconsin–Milwaukee',
  'University of Wyoming',
  'Utah State University',
  'Vanderbilt University',
  'Villanova University',
  'Virginia Commonwealth University',
  'Virginia Tech',
  'Wake Forest University',
  'Washington State University',
  'Washington University in St. Louis',
  'Wayne State University',
  'Wellesley College',
  'Wesleyan University',
  'West Virginia University',
  'Western Michigan University',
  'Wichita State University',
  'William & Mary',
  'Williams College',
  'Worcester Polytechnic Institute',
  'Yale University',
  'Yeshiva University',
] as const

export const US_UNIVERSITIES: readonly string[] = [...US_UNIVERSITIES_UNSORTED].sort((a, b) =>
  a.localeCompare(b),
)

const MAX_SUGGESTIONS = 12

export function filterUSUniversities(query: string, limit = MAX_SUGGESTIONS): string[] {
  const q = query.trim().toLowerCase()
  if (!q) return [...US_UNIVERSITIES].slice(0, limit)
  const matches: string[] = []
  for (const name of US_UNIVERSITIES) {
    if (name.toLowerCase().includes(q)) {
      matches.push(name)
      if (matches.length >= limit) break
    }
  }
  return matches
}
